root_dir: /srv/efs/.sshkeys

sub_dir:
  SISTMS:
    - sistms_sis
    - sistms_tms
  SKYSIS:
    - skysis_sis
    - skysis_sky
  SKYTMS:
    - skytms_tms
    - skytms_sky
  SKYKIK:
    - skykik_sky
    - skykik_kik

group_name: root

mode_permission: '700'

file_permissions: '600'