- name: Deploy systemd service
  template:
    src: efs-s3-uploader.service.j2
    dest: /etc/systemd/system/efs-s3-uploader.service
    owner: root
    group: root
    mode: '0644'

# Reload systemd
- name: Reload systemd
  command: systemctl daemon-reload

# Enable and start service
- name: Enable and start efs-s3-uploader service
  systemd:
    name: efs-s3-uploader
    state: started
    enabled: true