- name: Web Servers
  hosts: webservers
  become: true

  tasks:
    - name: Ensure apache is at the latest verion
      ansible.builtin.dnf:
        name: httpd
        state: latest

- name: DB servers
  hosts: databases
  become: true

  tasks:
    - name: Ensure postgresql is at the latest version
      ansible.builtin.dnf:
        name: postgresql
        state: latest
    - name: Ensure that postgresql is started
      ansible.builtin.service:
        name: postgresql
        state: started
