- name: Create all subdirectories
  file:
    path: "{{ root_dir }}{{ item.0.key }}/{{ item.1 }}"
    state: directory
    owner: "{{ owner_user }}"
    group: "{{ group_name }}"
    mode: "{{ mode_permission }}"
  loop: "{{ sub_folders | dict2items | subelements('value') }}"



