$ANSIBLE_VAULT;1.1;AES256
63633864373236316665646338623938643262323036336138306631356437386432346166636638
3037373038356139343666396638393665663634363963610a346166333064353536633930396461
34633234353166663931326330323766633138613532316333316363646165306361633939633530
6338333861393332630a303633356162663761653661316438373562336665343130613734663566
62383934383533646464373433643061373833313766326635336630343961366635613031616433
65346637303634383232303134303435306566383930656464393038396135663563343835336339
386439393466396437613034326664363131
