- name: Practice how can using the loop function.
  hosts: all
  become: true

  tasks:
    - name: install packages
      ansible.builtin.dnf:
        name: {{ item }}
        state: latest
      loop: ["nginx","docker"]
      changed_when: false
