sftp_watch_base: "/srv/efs/sftp"

# S3 bucket
sftp_s3_bucket: "h21.sftp.backup"

# Watcher executing node
sftp_watcher_node: "sftp-01"

sftp_watcher_script_path: "/usr/local/bin/sftp_s3_upload_watcher.sh"
sftp_watcher_service_name: "sftp_s3_upload_watcher.service"
sftp_watcher_log_file: "/var/log/sftp_s3_upload.log"

sftp_ignore_patterns:
  - "*.tmp"
  - "*.part"

# inotify events
sftp_inotify_events: "close_write,moved_to"
